---
- name: Create a mysql container
  docker_container:
    name: mysqldb
    image: mysql
    state: started
    ports:
      - "{{ port }}:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_pass }}"
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_pass }}"
