---
- hosts: digitalocean
  vars:
    do_token: "{{ access_key }}"

  tasks:
    - name: ensure ssh key exists
      user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/test

    - name: ensure key exists at DigitalOcean
      digital_ocean: 
        state: present
        command: ssh
        name: test_ssh_key
        ssh_pub_key: "{{ lookup('file', '~/.ssh/test.pub') }}"
        api_token: "{{ do_token }}"
      register: my_ssh_key

    - name: ensure the new droplet exists
      digital_ocean: 
        state: "{{ state }}"
        command: droplet
        name: "{{ item }}"
        size_id: "{{ size }}"
        region_id: "{{ region }}"
        image_id: "{{ image }}"
        ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
        api_token: "{{ do_token }}"
        unique_name: yes
      with_items: "{{ droplets }}"
      register: droplet_details

    - debug: msg="{{ item }}"
      with_items: "{{ droplet_details.results }}"

